# EGL mesa driver on cos7 are not working as expected, use alma8 instead
docker_image:                                       # [linux64]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [linux64]
