{% set component_name = "sensors" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "7_7.1.0" %}
{% set major_version = version.split('_')[0] %}
{% set version_package = version.split('_')[1] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ version }}.tar.gz
    sha256: b9b1aae94c20fa849015a203e9dbf4ed97e0152ae5f5c3de88cb4e44900ea6cd

build:
  number: 1

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - libgz-cmake3
        - libprotobuf
        - libgz-math7
        - libgz-common5
        - libgz-transport12
        - libgz-rendering7
        - libgz-msgs9
        - libgz-plugin2
        - libsdformat13
        - libarchive  # [osx]
        - ogre  {{ ogre }}
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/gz/{{ component_version }}/gz/{{ component_name }}.hh  # [not win]
        - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\include\\gz\\{{ component_version }}\\gz\\{{ component_name }}.hh exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/gazebosim/{{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Gazebo Sensors provides numerous sensor models designed to generate realistic data from simulation environments.

extra:
  feedstock-name: {{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
