schema_version: 1

context:
  component_name: sensors
  repo_name: ${{ "gz-" ~ component_name }}
  version: 10.0.0
  major_version: "10"
  name: ${{ repo_name }}
  component_version: ${{ component_name ~ major_version }}
  cxx_name: ${{ "lib" ~ name }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gazebosim/${{ repo_name }}/archive/${{ repo_name }}${{ major_version }}_${{ version }}.tar.gz
    sha256: 9841854013d61114f7a8d20b918df651404bf5a28d52dd0b4fc4caba5dc8aa08

build:
  number: 1

outputs:
  - package:
      name: ${{ cxx_name }}
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - libgz-cmake
        - libabseil
        - libprotobuf
        - libgz-math
        - libgz-common
        - libgz-transport
        - libgz-rendering
        - libgz-msgs
        - libgz-plugin
        - libsdformat
        - if: osx
          then:
            - libarchive
        - ogre 1.10.*
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}

    tests:
      - package_contents:
          include:
            - gz/${{ component_version }}/gz/${{ component_name }}.hh
          lib:
            - gz-${{ component_name }}
    # commented out due to strange failures on linux-aarch64 https://github.com/conda-forge/gz-sim-feedstock/issues/109
    #   - script:
    #       - cmake-package-check gz-${{ component_name }} --targets gz-${{ component_name }}::gz-${{ component_name }}
    #     requirements:
    #       run:
    #         - cmake-package-check
    #         - ${{ compiler('c') }}
    #         - ${{ compiler('cxx') }}

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    # commented out due to strange failures on linux-aarch64 https://github.com/conda-forge/gz-sim-feedstock/issues/109
    # tests:
    #   - script:
    #       - cmake-package-check gz-${{ component_name }} --targets gz-${{ component_name }}::gz-${{ component_name }}
    #     requirements:
    #       run:
    #         - cmake-package-check
    #         - ${{ compiler('c') }}
    #         - ${{ compiler('cxx') }}

about:
  homepage: https://github.com/gazebosim/${{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Gazebo Sensors provides numerous sensor models designed to generate realistic data from simulation environments.

extra:
  feedstock-name: ${{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
